# MODEL SETTINGS
WORLD_SCALE = 0.1

ANIMATION = 'Finger Taunt'

# CAMERAS SETTINGS
CAMERAS_NUMBER = 8
DISTANCE = 3
HEIGHT = 2
FOV = 35
NEAR_PLANE = 0.1
FAR_PLANE = 5 * DISTANCE

FIXED_CAMERAS = ["1", "4", "7"]

# IMAGE SETTINGS
IMAGE_SIZE = [960, 540]
IMAGE_MEAN = 100
IMAGE_STD = 25

# RENDERING SETTINGS
OUTPUT_RESOLUTION = 100  # percentage
BACKGROUND_COLOR = [127, 127, 127]

# ANIMATION SETTINGS
START_FRAME = 1
END_FRAME = 200
